"""empty message

Revision ID: 145d6ef7f919
Revises: None
Create Date: 2015-04-09 01:19:58.517654

"""

# revision identifiers, used by Alembic.
revision = '145d6ef7f919'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
